package com.example.androidprojectsettinginkotlin.constants

const val PREFS_LOGIN_ID = "LOGIN_ID"
const val PREFS_VISIBLE_BANNER_SCREEN = "VISIBLE_BANNER_SCREEN"
const val PREFS_VISIBLE_SPLASH_SCREEN = "VISIBLE_SPLASH_SCREEN"
const val PREFS_PERMISSION_DENY_COUNT = "PERMISSION_DENY_COUNT"

const val DIALOG_TYPE_PERMISSION = "DIALOG_TYPE_PERMISSION"
const val DIALOG_TYPE_PERMISSION_ONCE = "DIALOG_TYPE_PERMISSION_ONCE"
const val DIALOG_TYPE_PERMISSION_TWICE = "DIALOG_TYPE_PERMISSION_TWICE"